let shopItemData = [
    {
        id: "hhfhtvh",
        name: "Camo Comfort Fit",
        price: 80,
        desc: "Comfortable Button-up set.",
        img: "img/camo-fit.webp",
    },
    {
        id: "afafdrwf",
        name: "Purple King-Pin Suit",
        price: 65,
        desc: "Purple Bussiness (Event) Suit.",
        img: "img/purple-action.jpg",
    },
    {
        id: "hsswefa",
        name: "Breathable White Dress",
        price: 80,
        desc: "Lorem ipsum dolor sit amet.",
        img: "img/white-dress.webp",
    },
    {
        id: "htffhtvh",
        name: "White T-Shirt",
        price: 10,
        desc: "Lorem ipsum dolor sit amet .",
        img: "img/bini.jpg",
    },
    {
        id: "htwfgtvh",
        name: "Camo Comfort Fit",
        price: 65,
        desc: "Comfortable Button-up set.",
        img: "img/camo-fit.webp",
    },
    {
        id: "afafdgga",
        name: "Purple King-Pin Suit",
        price: 80,
        desc: "Purple Bussiness (Event) Suit.",
        img: "img/purple-action.jpg",
    },
    {
        id: "hdfsafa",
        name: "Breathable White Dress",
        price: 80,
        desc: "Lorem ipsum dolor sit amet .",
        img: "img/white-dress.webp",
    },
    {
        id: "ggwgweafga",
        name: "White T-Shirt Binnie Combo",
        price: 25,
        desc: "Lorem ipsum dolor sit amet .",
        img: "img/bini.jpg",
    },
    {
        id: "gafasgaw",
        name: "Camo Comfort Fit",
        price: 100,
        desc: "Comfortable Button-up set.",
        img: "img/camo-fit.webp",
    },
    {
        id: "gseffawf",
        name: "Purple King-Pin Suit",
        price: 200,
        desc: "Purple Bussiness (Event) Suit.",
        img: "img/purple-action.jpg",
    },
    {
        id: "gesfgshgea",
        name: "Breathable White Dress",
        price: 80,
        desc: "Lorem ipsum dolor sit amet .",
        img: "img/white-dress.webp",
    },
    {
        id: "gesfsegadwa",
        name: "White T-Shirt Binnie Combo",
        price: 25,
        desc: "Lorem ipsum dolor sit amet .",
        img: "img/bini.jpg",
    },
] // end of shopItemData
