let shopItemData = [
    {
        id: "hhfhtvh",
        name: "Camo  Fit",
        price: 80,
        desc: "Comfortable Button-up set.",
        img: "img/camo-fit.webp",
    },
    {
        id: "afafdrwf",
        name: "Purple King-Suit",
        price: 65,
        desc: "Purple Bussiness (Event) Suit.",
        img: "img/purple-action.jpg",
    },
    {
        id: "hsswefa",
        name: "Breathable Dress",
        price: 80,
        desc: "Lorem ipsum dolor sit amet.",
        img: "img/white-dress.webp",
    },
    {
        id: "htffhtvh",
        name: "White T-Shirt",
        price: 10,
        desc: "Lorem ipsum dolor sit amet .",
        img: "img/bini.jpg",
    },
    {
        id: "jfhgbvnscs",
        name: "Casual Shirt",
        price: 45,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img/work-velvet.jpg",
    },
    {
        id: "ioytrhndcv",
        name: "Office Shirt",
        price: 100,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img/office-comfort.jpg",
    },
    {
        id: "wuefbncxbsn",
        name: "T Shirt",
        price: 25,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img/spring-blouse.jpg",
    },
    {
        id: "thyfhcbcv",
        name: "Mens Suit",
        price: 300,
        desc: "Lorem ipsum dolor sit amet consectetur adipisicing.",
        img: "img/sway-set.jpg",
    },
];